In [1]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

# 建立Session，处理tensorflow的graph

In [4]:
sess = tf.Session()

# 创建Tensor

In [6]:
my_tensor = tf.zeros([1,20])
sess.run(my_tensor)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

# 使用Variable声明的变量需要sess中初始化，才可以使用

In [10]:
my_tensor = tf.Variable(tf.zeros([2,3]))
one_tensor = tf.Variable(tf.zeros([3,2]))
sess.run(my_tensor.initializer)
sess.run(one_tensor.initializer)
print(sess.run(my_tensor))
print(sess.run(one_tensor))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
fill_var = tf.Variable(tf.fill([2,3],-1))
sess.run(fill_var.initializer)

In [12]:
print(sess.run(fill_var))

[[-1 -1 -1]
 [-1 -1 -1]]


# 生成list的形式的变量，赋值常量


In [15]:
const_var = tf.Variable(tf.constant([1,2,3,4]))
const_var_fill = tf.Variable(tf.constant(-1,shape=[2,3]))


In [16]:
# 初始化
sess.run(const_var.initializer)
sess.run(const_var_fill.initializer)
print(sess.run(const_var))
print(sess.run(const_var_fill))

[1 2 3 4]
[[-1 -1 -1]
 [-1 -1 -1]]


# 创建Tensor，使用序列或者范围函数


In [20]:
line_var = tf.Variable(tf.linspace(start=0.,stop=1.,num=3))
sequence_var = tf.Variable(tf.range(start=6,limit=15,delta=3))
sess.run(line_var.initializer)
sess.run(sequence_var.initializer)
print(sess.run(line_var))
print(sess.run(sequence_var))

[0.  0.5 1. ]
[ 6  9 12]


In [22]:
# 随机数初始化
random_var = tf.random_normal([2,3],mean=0.,stddev=1.)
runif_var = tf.random_uniform([2,3],minval=0,maxval=4)
print(sess.run(random_var))
print(sess.run(runif_var))

[[ 1.1397682   1.0403638   0.1624016 ]
 [-0.27518523 -2.5282724   0.8822056 ]]
[[2.4623146  2.4991326  1.972332  ]
 [2.197977   0.55549765 1.7756772 ]]
