In [2]:
import numpy as np
import tensorflow as tf


In [3]:
sess = tf.Session()

## 声明对角矩阵

In [5]:
identity_matrix = tf.diag([1.,1.,1.])
print(sess.run(identity_matrix))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 声明2*3的矩阵

In [7]:
A = tf.truncated_normal([2,3])
print(sess.run(A))

[[-0.7862806   0.99463224 -0.03162075]
 [-1.2721673  -0.03203826  0.49829146]]


## 声明常量矩阵

In [9]:
B = tf.fill([2,3],5.)
print(sess.run(B))

[[5. 5. 5.]
 [5. 5. 5.]]


## 创立平均分布的矩阵

In [10]:
C = tf.random_uniform([2,3])
print(sess.run(C))

[[0.8095732  0.7898878  0.52591956]
 [0.30048668 0.76026535 0.03902364]]


## numpy矩阵转tensor

In [12]:
np_array = np.array([[2,3,4],[3,45,6],[-1,34,56]])
tensor_array = tf.convert_to_tensor(np_array)
print(sess.run(tensor_array))

[[ 2  3  4]
 [ 3 45  6]
 [-1 34 56]]


## Tensorflow中的矩阵操作

矩阵加法

In [13]:
print(sess.run(A+B))

[[5.718998  3.6870327 6.04958  ]
 [5.687171  5.617752  5.1375437]]


矩阵乘法

In [16]:
print(sess.run(tf.matmul(A,identity_matrix))))

[[ 0.62266564  1.0696478  -0.49846217]
 [ 0.17391601 -0.14357902  1.5956199 ]]


矩阵转置

In [17]:
print(sess.run(tf.transpose(C)))

[[0.8765303  0.08134377]
 [0.12078834 0.32538962]
 [0.23056114 0.38544822]]


矩阵行列式

In [21]:
print(sess.run(tf.matrix_determinant(identity_matrix)))

1.0
